apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-repo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-repo-web
  template:
    metadata:
      labels:
        app: test-repo-web
    spec:
      serviceAccountName: log-reader-sa
      containers:
      - name: test-repo-web
        image: capybariana/test-repo-web:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-reader-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: log-reader-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: log-reader-role
subjects:
- kind: ServiceAccount
  name: log-reader-sa